### ISSUE TITLE
Refactor frontend structure

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-ui#121]
We need to refactor our code. It is extremely difficult to follow, components are placed everywhere and the same modules are included multiple times because our structure doesn't allow for a single inclusion. 

I will comment on this issue very soon with a structure that we can implement. This will make following our code much easier not just for us, but also everyone else that will look at our code.

**Comment by annamarieHelberg** [comment]
The structure we can follow is: Having only the navbar, userbar and auth.guard in the shared folder. This is logical as these things get shared by all pages. The other folder/files in the current _shared folder can be moved to a pages directory. This include the refresh page. We keep the classes, services and models as is.

We will also need to improve on the logic that the home.html is the new app.html (? or so it seems) as this makes including libraries extremely more complicated than necessary and we have duplicate imports lower down in the structure.

Also, the user management branch has the models, services and pages all in one directory which we will need to move.

**Comment by egeldenhuys** [comment]
> The other folder/files in the current _shared folder can be moved to a pages directory. This include the refresh page. 

I forgot to move the refresh page while implementing the Login page.

> We will also need to improve on the logic that the home.html is the new app.html (? or so it seems) as this makes including libraries extremely more complicated than necessary and we have duplicate imports lower down in the structure.

The HomeModule/Component was introduced so we can display single components at the root level without having to add extra logic to hide the user bar and nav bar. I was planning on lazy loading the HomeModule but lost sight of that goal along the way. If the old structure will make things significantly simpler then it can be reverted and logic added to hide the nav and user bar.

> Also, the user management branch has the models, services and pages all in one directory which we will need to move.

To me it made sense to keep related components in their own folder. Then it is more clear the the components/pages in that folder belong to the same module in that folder. This I based on [Overall structural guidelines - style 04-06](https://angular.io/guide/styleguide#style-04-06) and [Folders-by-feature structure - style 04-07](https://angular.io/guide/styleguide#style-04-07)

I currently have the directory structure:
```
└── user-management
    ├── models
    │   ├── api-response.model.ts
    │   └── user.model.ts
    ├── shared
    │   ├── user.service.spec.ts
    │   └── user.service.ts
    ├── user-create
    │   ├── user-create.component.css
    │   ├── user-create.component.html
    │   ├── user-create.component.spec.ts
    │   └── user-create.component.ts
    ├── user-edit
    │   ├── user-edit.component.css
    │   ├── user-edit.component.html
    │   ├── user-edit.component.spec.ts
    │   └── user-edit.component.ts
    ├── user-list
    │   ├── user-list.component.css
    │   ├── user-list.component.html
    │   ├── user-list.component.spec.ts
    │   └── user-list.component.ts
    ├── user-management.module.ts
    └── user-management-routing.module.ts
```

Would that then translate to the following?
```
.
├── _models
│   ├── api-response.model.ts
│   └── user.model.ts
├── _modules
│   ├── user-management.module.ts
│   └── user-management-routing.module.ts
├── _pages
│   ├── user-create
│   │   ├── user-create.component.css
│   │   ├── user-create.component.html
│   │   ├── user-create.component.spec.ts
│   │   └── user-create.component.ts
│   ├── user-edit
│   │   ├── user-edit.component.css
│   │   ├── user-edit.component.html
│   │   ├── user-edit.component.spec.ts
│   │   └── user-edit.component.ts
│   └── user-list
│       ├── user-list.component.css
│       ├── user-list.component.html
│       ├── user-list.component.spec.ts
│       └── user-list.component.ts
└── _services
    ├── user.service.spec.ts
    └── user.service.ts
```

If you can point me to the style guide we are using I will adapt my work accordingly :+1: 

> and we have duplicate imports lower down in the structure

What are the consequences of this?

**Comment by annamarieHelberg** [comment]
There are no official structure for the styling but the way we have it is confusing. Compiax showed me how they do their structuring which is a lot simpler and easy to implement. 

> The HomeModule/Component was introduced so we can display single components at the root level without having to add extra logic to hide the user bar and nav bar. I was planning on lazy loading the HomeModule but lost sight of that goal along the way. If the old structure will make things significantly simpler then it can be reverted and logic added to hide the nav and user bar. 

There are other ways of implementing it but out current structure complicates it. If I recall correctly, we can use the auth service or the auth.guard to do the same job.

> To me it made sense to keep related components in their own folder. Then it is more clear the the components/pages in that folder belong to the same module in that folder

No, this is not what I meant. The user-management will be a folder in the 'pages' directory and it will contain user-create, -edit, -list. So the idea for the first structure is correct except that the models and services inside the user-managment folder must be moved to the models and services directories respectively. 

So the structure will be:
-classes
-shared
    -auth.guard
    -navbar 
-services
    -auth.service
    -volumes.service
    -user-management.service
-models
    -user.model
-pages
    -volumes
    -user-management
         -user-list
         -user-edit

... etc.

I hope that makes sense. But, each component will be in its own folder but all the components will be under the pages directory. If we don't follow this approach the structures becomes cluttered and difficult to follow

**Comment by annamarieHelberg** [comment]
> What are the consequences of this?

It is bad practice and makes following the code difficult. There are no serious complications but it will make the code neater.

[This](https://medium.com/@cyrilletuzi/understanding-angular-modules-ngmodule-and-their-scopes-81e4ed6f7407) explains a more about where/why to implement modules

**Comment by Jason-vh** [comment]
I figured I'd just jump in here to elaborate and expand on what Anna-Marié is saying:

While there are a plethora of accepted conventions for Angular, we found a particular structure that worked for us by being particularly scalable and easy to follow. While it is not mandatory to follow it, I'll provide an explanation of it as well as our thinking behind it in the hopes that it will help your discussion and project.

Using examples from your existing code and the above discussion (and Evert's nifty tree structure), it would look something like this:

```
├─ _models
│ ├── user.model.ts
│ └── ...other models ...
│
├─ _shared
│ ├── navbar
│ │   ├── navbar.component.ts
│ │   └── ... other navbar files ...
│ └── userbar
│     ├── userbar.component.ts
│     └── ... other userbar files ...
│
├── _services
│   ├── user.service.ts
│   ├── user.service.spec.ts
│   └── ... other services and their spec files ...
│
└── _pages
    ├── user-management
    │   ├── user-create
    │   │   ├── user-create.component.css
    │   │   ├── user-create.component.html
    │   │   ├── user-create.component.spec.ts
    │   │   └── user-create.component.ts
    │   ├── user-edit
    │   │   ├── user-edit.component.css
    │   │   ├── user-edit.component.html
    │   │   ├── user-edit.component.spec.ts
    │   │   └── user-edit.component.ts
    │   ├── user-list
    │   │   ├── user-list.component.css
    │   │   ├── user-list.component.html
    │   │   ├── user-list.component.spec.ts
    │   │   └── user-list.component.ts
    │   ├── user-management.module.ts
    │   └── user-management-routing.module.ts
    ├── home
    │   └── ... files for the home page ...
    ├── login
    │   └── ... files for the login page ...
    └── ... other pages ...
```

The structure is separated into four main sections:
- _models
- _shared
- _services
- _pages

Each folder in `_pages`_ contains the components and *view logic* for a specific page, such as the home page or login page. These components should obviously be modularised as feasible - that is, each page will contain 'feature folders' for each feature in the page. Your separation of the elements of the user management page is an perfect example of this.

A page should contain _only_ the components relevant to it's purpose. If a component is shared (typically headers and footers), they should be placed in the `_shared` folder. This folder is intended for shared *components*, and shouldn't contain services and other logic. In addition, only view logic should be contained in a page, with any logic relating to the backend being placed in service/s (typically the HTTP requests) and model(s) (typically logic related to parsing the HTTP requests to specific object representations).

`_services` should contain only services and their unit tests. In our structure we have it in a flat directory structure, but a possible improvement is to have each service and it's corresponding `.spec` in separate folders.

And finally, `_models` should only contain the models and their logic, as well as any unit tests thereof.

There is little need to have models and services in the `_shared` folder, as they tend to be inherently shared, causing the resulting `_shared` folder to become quite enormous.

The reason for the underscored folder names is because we initially only extracted the models, services and shared folders out, with the underscores helping to delineate them from the page folders. With the addition of `_pages`, the underscores are actually no longer necessary.

I'd like to reiterate that it is not a requisite for you to follow this, I'm just providing it for reference.

Edit: But I do concur with Anna-Marié that refactoring and cleaning up the code structure will help with both development and maintaining the code.

**Comment by egeldenhuys** [comment]
Thank you for the explanation @annamarieHelberg  and @Jason-vh. I think I am now on the same page.
The proposed directory structure does make more sense.

So the only complication left to solve is the Home Module.

An alternative to having only `<router-outlet>` in `AppComponent` is to use the following as it was before, but with logic to hide the user and nav bar: (Not tested)
```html
<app-user-bar [hidden]="!isLoggedIn"></app-user-bar>
<div class="container-fluid page-container">
  <div class="row">

    <div class="col-md-2 col-xs-1" [hidden]="!isLoggedIn">
      <app-navbar></app-navbar>
    </div>

    <div class="col-md-10 col-xs-11" [hidden]="!isLoggedIn">
      <router-outlet></router-outlet>
    </div>
 
    <!-- To get rid of the col-md-10 class used when the user is logged in -->
    <router-outlet [hidden]="isLoggedIn"></router-outlet>

  </div>
</div>
```

**Comment by annamarieHelberg** [comment]
Yes, @egeldenhuys that code snippet is what I had in mind. It will significantly improve the understandability of the code as we can completely remove the logic from the page

**Comment by annamarieHelberg** [comment]
@egeldenhuys, @CDuPlooy, @FJMentz can we decide on this matter by Friday? If we want to refactor this needs to happen as soon.

**Comment by egeldenhuys** [comment]
I am happy with the plan to refactor the directory structure and remove the Home Module

**Comment by annamarieHelberg** [comment]
Thank you @egeldenhuys I will look into this

**Comment by CDuPlooy** [comment]
I don't recall exactly why components were thrown into _shared; Perhaps at the time we were rushing for a demo.  The suggested changes seem logical, I'm on board. :)

Some clarification; The home component was added because we had nothing to default to when the route specified isn't configured to any component.  I did mention this in a meeting, it could be removed at any time - it was placed as is so that everyone would be aware of the fact that we need a default route. Naming it home seemed appropriate.

**Comment by annamarieHelberg** [comment]
I could only test the branch now as I had to redo my setup on my computer. I see that my css magics fail on  another monitor for the login page. The github logo moves down. And I get 500 errors when requesting the task list/card view and services list view. @egeldenhuys  is it a problem on my side?

Edit: I am aware that 500 errors mean it's server errors but I want to know if you get the same errors

**Comment by devosray** [comment]
@egeldenhuys I'm running into the same issue on the login page:
![image](https://user-images.githubusercontent.com/5329962/42825927-71208b72-89e3-11e8-888f-31f857fa4be4.png)

I am not getting server errors though.

**Comment by egeldenhuys** [comment]
I will investigate the server errors

**Comment by egeldenhuys** [comment]
@annamarieHelberg What version of Docks API are you using?

**Comment by annamarieHelberg** [comment]
@egeldenhuys I have the latest version of Docks API now but I still get 503 errors when requesting those pages.

**Comment by annamarieHelberg** [comment]
I fixed it @egeldenhuys . There's nothing a good uninstall and re-install can't fix 😌
