### ISSUE TITLE
Revert Home Module

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#124]
As discussed in #121 the Home Module can be removed and replaced with something similar to the following in the `AppComponent`

(Not tested)
```html
<app-user-bar [hidden]="!isLoggedIn"></app-user-bar>
<div class="container-fluid page-container">
  <div class="row">

    <div class="col-md-2 col-xs-1" [hidden]="!isLoggedIn">
      <app-navbar></app-navbar>
    </div>

    <div class="col-md-10 col-xs-11" [hidden]="!isLoggedIn">
      <router-outlet></router-outlet>
    </div>
 
    <!-- To get rid of the col-md-10 class used when the user is logged in -->
    <router-outlet [hidden]="isLoggedIn"></router-outlet>

  </div>
</div>
```

**Comment by annamarieHelberg** [comment]
I will test this tomorrow and give you feedback on what I find. Thanks @egeldenhuys

**Comment by annamarieHelberg** [comment]
I've been struggling with this for a while now and came to the conclusion that in order to implement this we need to do it when we refactor. But, when I created my login page I implemented it with the ngIf so I know it works. 

I will follow up on this as soon as we have decided what will happen with the refactor (#121 ).

**Comment by annamarieHelberg** [comment]
This is handled in #121.
