### ISSUE TITLE
Move from Angular.Material to Bootstrap

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks-ui#26]
Any comments on this? I think it is worth it to move over to bootstrap as it more 'familiar' to most of us and also there is a lot of examples and support for bootstrap.

**Comment by CDuPlooy** [comment]
I will do this either tonight or tomorrow while preserving the services.
Currently for IMY we are using [this](https://github.com/DownTownCookieFrenzy/play-music).

I will also be changing the directory structure. Any comments on this, requested changes maybe.

**Comment by egeldenhuys** [comment]
After looking at the docs for Bootstrap 4 and Angular Material, they both offer the same components. Bootstrap has more documentation and will probably have more examples since it is not restricted to Angular.

Since it is more familiar I am okay with switching over to Boostrap. What will be the implications on the current interface?

**Comment by FJMentz** [comment]
As far as I know we'll just have to redo some styling, but taking into consideration what feedback we received I'm looking into a different approach on the cards so the posibility that everything will have to change is already out there. Also the html that will be affected will be quick and easy to change.

So in conclusion I feel the impact of switching over will be minimal to the existing project but will help a lot for further development.

**Comment by egeldenhuys** [comment]
+1 for Bootstrap

**Comment by CDuPlooy** [comment]
Because of the changes to the directory structure we won't be able to copy paste any code from the angular branch ( not without modification anyway ). In the bootstrap_migration branch I have already added an example of how to get a list of containers and serialise them to container models. I think this is the most elegant approach for now. 

Note that each service corresponds to an entity listed in [Docker Engine API](https://docs.docker.com/engine/api/v1.37/). We will hold off on implementing anything in the services for now because the back-end is still adding authorisation & permissions. For now we should probably look at creating enums for the different REST return codes to correspond to the API documentation. 

Assuming the responses generated by the backend stay the same we could use dummy responses to test and implement some of the frontend for now. Would be nice if @egeldenhuys  or @devosray could confirm this.

**Comment by egeldenhuys** [comment]
For now you can assume that the API specification follows the Docker API.
The name of endpoints on Docks will change to something like `POST /api/services/{id}/logs` and authentication will be added to the request body. 

The response may be modified to include two objects: a Status and a Response. Where status will include a meaningful status message, and response will be the response from Docker.

**Comment by CDuPlooy** [comment]
Closed by 6dfaf0ddbb4ff86a7b53ddfe40960bc092fbbc5b
