### ISSUE TITLE
Screen Designs

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-ui#45]
A quick stub, update details here please.

- [ ] General Layout
- [ ] Login
- [ ] Deploy pre configured stack
- [ ] Containers
- [ ] Services
- [ ] Stacks
- [ ] Logs
- [ ] Networks
- [ ] Volumes
- [ ] Tasks

**Comment by egeldenhuys** [comment]
Originally posted by @annamarieHelberg on TripleParity/docs/issues/15

> I agree and we should keep the design simple but elegant. There are quite a few templates (these are Angular 2 or 4 but they will probably still spark some creativity: https://bootstrapbay.com/blog/free-angular-templates/ and https://colorlib.com/wp/angular-2-components/) that we can look at. The first link lists templates for dashboards and the other link is just for inspiration when it comes to components. This is also a colour scheme designer (http://paletton.com/#uid=10P0u0kllllaFw0g0qFqFg0w0aF) to look at.

**Comment by egeldenhuys** [comment]
Waiting for @Paulo-W to post links to the design documents

**Comment by egeldenhuys** [comment]
[View Screen Designs on Google Drive](https://drive.google.com/open?id=12N5U8m1kqp8araVw38xcSJrDwJq-omEK)

**Comment by egeldenhuys** [comment]
I see there are many different design ideas in the Drive folder, which parts of those ideas will make it into the final design (for now)?

**Comment by ghost** [comment]
For now the idea is a hybrid of the following ideas;
 - selecting an operation for a component (task, volume, network etc etc) from a drop down menu in the idea 3 folder 
- The tab view in idea 4. 

The idea behind this is that the user will be able to click on an operation which takes them to the right tab menu for that operation, but if they want to perform a separate operation they will be able to access it via the tab instead of going back to the view page.

**Comment by egeldenhuys** [comment]
Using Swarmpit as a reference now
