### ISSUE TITLE
Promises Or Observables 

### ISSUE THREAD

**Issue by CDuPlooy** [TripleParity/docks-ui#6]
See this [search](https://www.google.co.za/search?q=Promises+vs+Observables&oq=Promises+vs+Observables&aqs=chrome..69i57j35i39j0l4.3584j0j7&sourceid=chrome&ie=UTF-8)

I believe someone stated that promises are more sequential? In either case we should probably make a decision as soon as possible.

**Comment by FJMentz** [comment]
Aren't Promises usually asynchronous unless forced not to be?

**Comment by Jason-vh** [comment]
Promises are 100% asynchronous, designed to solve the so-called 'callback hell' that JavaScript and it's derivatives bring.

Edit: I've included a (very) brief description of my thoughts regarding the difference between Promises and Observables. I advise that you read up on both though, as choosing which to use is entirely user preference at the end of the day.

There are three main differences (for me) between Promises and Observables:

- Promises only`resolve` once, whereas an Observable can `emit` multiple times
- You can use async/await with Promises (and hence the 'more sequential' possibility of promises)
- As a result, the code for an await'ed Promise is neater than an Observable.

Note that by default, every HTTP method in Angular returns an Observable.

Consider the case of an HTTP request (for example, a GET request to fetch a users details), which will only return once. Using an Observable would look something like this:
```javascript
getUser(username) {
    return this.http.get(`localhost:3000/user/${username}`)
    // this function returns an Observable
}
```
```javascript
async ngOnInit() {
  // Some component somewhere that needs to fetch a user
  getUser('jason').subscribe(result => {
    this.user = result
    // Do things with this.user
  })
  // The function will continue to execute, regardless of whether the user has been fetched yet
}
```

Doing this with a Promise would only look marginally different:
```javascript
getUser(username) {
    return this.http.get(`localhost:3000/user/${username}`).toPromise()
    // this function returns a Promise, due to the use of .toPromise()
}
```
```javascript
async ngOnInit() {
  getUser('jason').then(result => {
    this.user = result
    // Do things with this.user
  })
  // The function will continue to execute, regardless of whether the user has been fetched yet
}
```

**However**, one can use async/await when Promises are used:
```javascript
getUser(username) {
    return this.http.get(`localhost:3000/user/${username}`).toPromise()
    // exactly the same as above
}
```
```javascript
async ngOnInit() {
  this.user = await getUser('jason')
  // The function only continues to execute after the user has been fetched
  // Do things with the user
}
```

Note the use of `async` in the function definition, and `await` when calling `getUser()`. Also note how the asynchronicity of the HTTP request has been abstracted away, and how much cleaner the code looks.

You do need to use Observables when a function may return multiple times though. Consider the following example:
```javascript
route.params.subscribe(params => {
  console.log(params)
})
```
In Angular, `route.params` contains the parameters in the URL - for example, if the route was configured to be `/user/:username` and the url is `/user/jason`, `params` would equal `{ username: 'jason' }`.

In this example, an Observable is used because the user can navigate around the website multiple times. If the user now navigated to `/user/evert`, the Observable would fire with the value `{ username: 'evert' }`. Using a Promise here wouldn't make sense, as the username would stay as `'jason'`, no matter what the URL became.

**Comment by CDuPlooy** [comment]
I suppose this issue was more about opening discussion between our team members to decide on either Observables  or Promises. 

I thought about this and read up on it. We can also something similar to what netflix uses as described in this [thread](https://github.com/ReactiveX/rxjs/issues/556) by jayphelps. Or simply use toPromise if we want to await. 

IMO we should use Observables because that is what the Angular API returns and then await the converted promise ( should we need to do so ). Also because Observables can have many subscribers I think it'd be better to default to those so that if we later do need that functionality it is readily available. What do the rest of you think? There is a [short video](https://www.youtube.com/watch?v=2LCo926NFLI) on Observables which I found quite interesting.

Also thank you @Jason-vh for your reply and input in the matter.

**Comment by CDuPlooy** [comment]
We'll be using Observables.
